store:
  "paths":
    - "Store/**.js"
    - "Cart/**.html"
  "description":
    - Please check the following store pages (general)
  "items":
    - [Store checklist 1](https://www.google.com/)
    - Store checklist 2
    - Store checklist 3
blog:
  "paths":
    - "Blog/**.php"
    - "Blogger/**.ts"
  "description":
    - Please check the following blog pages (general)
  "items":
    - Blog checklist 1
    - Blog checklist 2
    - Blog checklist 3
test:
  "paths":
    - "**.java"
  "description":
    - Please check the following test files
  "items":
    - Test checklist 1
    - Test checklist 2
