name: validate
description: validate
inputs:
  validate:
    description: 'Should validate after deploying'
    required: true
    default: 'true'

runs:
   using: 'composite'
   steps:
      - name: VALIDATING
        if: inputs.validate == 'true'
        shell: bash
        run: echo "VALIDATING"

      - name: VALIDATING EXPRESSION
        if: ${{ inputs.validate }} == 'true'
        shell: bash
        run: echo "VALIDATING EXPRESSION"

      - name: VALIDATING JUST EXPRESSION
        if: ${{ inputs.validate }}
        shell: bash
        run: echo "VALIDATING JUST EXPRESSION"

      - name: PRINT EXPRESSION
        run: echo ${{ inputs.validate }}
        shell: bash

      - name: WEIRD EXPRESSION 1
        if: false == 'true'
        shell: bash
        run: echo "WEIRD EXPRESSION 1"

      - name: WEIRD EXPRESSION 2
        if: ${{ inputs.validate }} == true
        shell: bash
        run: echo "WEIRD EXPRESSION 2"

      - name: TEST
        shell: bash
        run: echo "TEST"
