name: validate
description: validate
inputs:
  validate:
    description: 'Should validate after deploying'
    required: true
    default: 'true'

runs:
   using: 'composite'
   steps:
      - name: VALIDATING
        if: inputs.validate == 'true'
        shell: bash
        run: echo "VALIDATING"

      - name: VALIDATING EXPRESSION
        if: ${{ inputs.validate }} == 'true'
        shell: bash
        run: echo "VALIDATING EXPRESSION"


      - name: TEST
        shell: bash
        run: echo "TEST"
