name: branch change to master
on:
   pull_request:
      types: edited

jobs:
   base-branch-change-rebuild-assets:
      if: |
         github.event.action == 'edited' &&
         github.event.changes.base && !github.event.changes.body && !github.event.changes.title &&
         github.event.changes.base.ref.from != 'master' && github.base_ref == 'master'
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Dump GitHub context
           env:
              GITHUB_CONTEXT: ${{ toJSON(github) }}
           run: echo "$GITHUB_CONTEXT"
