name: branch change to master test
on:
   pull_request:
      types: edited

jobs:
   base-branch-change-rebuild-assets:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Dump GitHub context
           env:
              GITHUB_CONTEXT: ${{ toJSON(github) }}
           run: echo "$GITHUB_CONTEXT"
