name: Trigger testintenv.yml workflow on base branch change

on:
  pull_request:
    types:
      - edited
jobs:
  check-pr:
    if: github.event.action == 'edited' && github.event.changes.base.ref.from != 'master' && github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: trigger testintenv.yml workflow on base branch change
        run: gh workflow run testintenv.yml --ref ${{ github.head_ref }}
        env:
           GH_TOKEN: ${{ github.token }}
