name: QA 
on:
   pull_request:
   push:
      branches:
         - master

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: checklist_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get head commit for push event
        run: |
          echo "OVERRIDE_BRANCH=('${{ toJSON(github.event.commits) }}' | jq ".[length - 2].id")" >> $GITHUB_ENV
        shell: bash

      - name: Print job name
        run: |
          echo "Before:"
          echo ${{ github.event.before }}
          echo "Afterr:"
          echo ${{ github.event.after }}
          echo "head commit:"
          echo ${{ github.event.head_commit.id }}
          echo ${{ github.event.commits[0].id }}
          echo '${{ toJSON(github.event.commits) }}' 
          echo '${{ toJSON(github.event.commits) }}' | jq ".[length - 2].id"
          echo $NUM
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          NUM: ${{ github.event.pull_request.head.sha || $OVERRIDE_BRANCH }}
        shell: bash
