name: QA 
on: [pull_request, workflow_run]

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: checklist_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: ./.github/actions/setup-ci-env-vars
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_JOB_NAME: ${{ github.job }}
      - name: Print job name
        run: |
          echo ${{ github.job }}
          echo ${{ github.event.pull_request.updated_at }}
          echo ${{ github.event.workflow_job }}
          echo ${{ github.event.workflow_job.started_at }}
          echo $TESTING_HERE
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          TESTING_HERE: ${{ toJson(job) }}
    
  testing_job1:
    runs-on: ubuntu-latest
    name: testing_job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: ./.github/actions/setup-ci-env-vars
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_JOB_NAME: ${{ github.job }}
      - name: Print job name
        run: |
          echo ${{ github.job }}
