name: QA 
on: pull_request

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: Checklist
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checklist  
        uses: batbattur/contextual-qa-checklist-action@69aa588807d6b71c7e4224c12461a4e0070af2e6
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          input-file: '.github/QAchecklist.yml'
          comment-header: "Hey, by the way, we noticed the following changes:"
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Testing Github API
        uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/batBattur/All/actions/runs/${{github.run_id}}/jobs
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo ${{ fromJson(steps.get_latest_release.outputs.data) }} | jq '.html_url'
