name: QA 
on:
   pull_request: 
   push:
      branches:
         - master

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: checklist_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Print commits
        run: echo '${{ toJSON(github.event.commits) }}' 
        shell: bash

      - name: Print github.sha for push event
        run: echo ${{ github.sha }}
        
      - name: Get head commit for push event
        run: |
          echo "OVERRIDE_BRANCH=$(echo $COMMITS_JSON | jq ".[length - 2].id")" >> $GITHUB_ENV
          echo "$OVERRIDE_BRANCH"
        shell: bash
        env:
          COMMITS_JSON: ${{ toJSON(github.event.commits) }}

