name: QA 
on:
   pull_request:
   push:
      branches:
         - master

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: checklist_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print job name
        run: |
          echo "Before:"
          echo ${{ github.event.before }}
          echo "After:"
          echo ${{ github.event.after }}
          echo "heada Commit:"
          echo ${{ github.event.head_commit.id }}
          echo ${{ github.event.commits[0] }}
          echo ${{ github.event.commits[1] }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
    
