name: QA 
on: pull_request

jobs:
  checklist_job:
    permissions: 
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    name: Checklist
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checklist  
        uses: batbattur/contextual-qa-checklist-action@1.2
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          input-file: 'ChecklistFolder/QAchecklist.yml'
          comment-header: "Hey, by the way, we noticed the following changes:"
