name: QA 
on: pull_request

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: Checklist
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: ./.github/actions/setup-ci-env-vars
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Testing
        run: |
          echo ${{ github.job }}
  testing_job1:
    runs-on: ubuntu-latest
    name: Checklist1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

