name: QA 
on:
   pull_request: 
   push:
      branches:
         - master

concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
   cancel-in-progress: true


jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: checklist_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout code
        run: jq --version
        
      - name: Test output QUEUE_LOCKED=false
        id: check_queue
        run: echo "QUEUE_LOCKED=true" >> $GITHUB_OUTPUT
        
      - name: Echo QUEUE_LOCKED
        run: echo "${{ steps.check_queue.outputs.QUEUE_LOCKED }}"

      - name: Deploy
        if: steps.check_queue.outputs.QUEUE_LOCKED == 'false'
        run: echo "hi"
     
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJSON(github) }}
#         run: echo "$GITHUB_CONTEXT"

#       - name: Print TESTING
#         run: |
#            echo ${{ github.workflow  }}
#            echo ${{ github.ref }}
#            echo ${{ github.run_number }}
#         shell: bash
        
#       - name: Print github.sha 
#         run: echo ${{ github.sha }}

#       - name: Print github.event.pull_request.head.sha
#         run: echo ${{ github.event.pull_request.head.sha }}        
        
        
#       - name: Get head commit sha from the push event and set it to push_head_commit env
#         run: echo "push_head_commit=$(echo $COMMITS_JSON | jq ".[length - 2].id")" >> $GITHUB_ENV
#         shell: bash
#         env:
#             COMMITS_JSON: ${{ toJSON(github.event.commits) }}

#       - name: Print sha of the head commit
#         run: echo "$push_head_commit"
#         shell: bash
