name: QA1
on:
   pull_request: 
   push:
      branches:
         - master

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
   cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  checklist_job1:
    runs-on: ubuntu-latest
    name: checklist_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Testing
        run: sleep 5m
        shell: bash
        
  checklist_job2:
    runs-on: ubuntu-latest
    name: checklist_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Testing
        run: sleep 5m
        shell: bash
