name: QA 
on:
   pull_request: 
   workflow_dispatch:
   push:
      branches:
         - master

concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
   cancel-in-progress: true


jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: checklist_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: RUN ATTEMPT AND NUMBER
        run: |
           echo "RUN ATTEMPT: ${{ github.run_attempt }}"
           echo "RUN NUMBER: ${{ github.run_number }}"

      - name: TEST 1
        if:  ${{ github.run_attempt > 1 }} 
        run: |
           echo "RUN ATTEMPT: ${{ github.run_attempt }}"
           echo "RUN NUMBER: ${{ github.run_number }}"

      - name: TEST 2
        if:  github.run_attempt > 1
        run: |
           echo "RUN ATTEMPT: ${{ github.run_attempt }}"
           echo "RUN NUMBER: ${{ github.run_number }}"
           
      - name: TEST 3
        if:  github.run_attempt == 1
        run: |
           echo "RUN ATTEMPT: ${{ github.run_attempt }}"
           echo "RUN NUMBER: ${{ github.run_number }}"

      - name: Checkout code
        run: jq --version

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

        
  checklist_job1:
    runs-on: ubuntu-latest
    name: checklist_job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Print TESTING
        run: |
           echo ${{ github.workflow  }}
           echo ${{ github.ref }}
           echo ${{ github.run_number }}

      - name: Checkout code
        run: exit 1

      - name: Deploy
        if: failure()
        run: |
           echo "hi"
           echo ${{ env.is_rerun }}
           echo ${{ env.is_rerun == 'true' }}
           echo ${{ env.is_rerun != 'true' }}


  checklist_job12
    runs-on: ubuntu-latest
    name: checklist_job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: sleep 180
        run: echo "$GITHUB_CONTEXT"

      - name: Print TESTING
        run: |
           echo ${{ github.workflow  }}
           echo ${{ github.ref }}
           echo ${{ github.run_number }}

      - name: Deploy
        if: cancelled()
        run: |
           echo "this was cancelled"
