name: QA 
on: pull_request

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: Checklist
    steps:
      - name: Get Action Job Info
        uses: octokit/request-action@v2.x
        id: get_action_job_data
        with:
           route: GET /repos/{owner}/{repo}/actions/runs/${{github.run_id}}/jobs
           owner: batbattur
           repo: All
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get job url
        id: get_action_job_url
        run:
           | # The following works when there is only one job in the workflow, e.g., phpunit/unit workflow
           echo "::set-output name=job-url::$(echo $job_data_json | jq '.jobs | .[] | .html_url' | sed 's/?check_suite_focus=true//g')"
        env:
           job_data_json: ${{ steps.get_action_job_data.outputs.data }}
        shell: bash
      - name: Print url
        run: |
          echo "${{ steps.get_action_job_url.outputs.job-url }}"
  checklist_job1:
    runs-on: ubuntu-latest
    name: Checklist1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Get Action Run Info
        uses: octokit/request-action@v2.x
        id: get_action_run
        with:
          route: GET /repos/{owner}/{repo}/actions/runs/${{github.run_id}}/jobs
          owner: batbattur
          repo: All
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get job url
        run: |
          echo "WORKFLOW_JOB_URL=$(echo $json_var | jq '.jobs | .[] | .html_url' | sed 's/?check_suite_focus=true//')" >> $GITHUB_ENV
        env:
          json_var: ${{ steps.get_action_run.outputs.data }}
      - name: Print url
        run: |
          echo $WORKFLOW_JOB_URL
