name: QA 
on:
   pull_request: 
      types: [opened, synchronize, reopened, edited]
   workflow_dispatch:
   push:
      branches:
         - master

concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
   cancel-in-progress: true


jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: checklist_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Print run_id
        run: |
           echo ${{ github.run_id  }}

      - name: Deploy
        if: cancelled()
        run: |
           echo "this was cancellasdasded"

  checklist_job1:
    runs-on: ubuntu-latest
    name: checklist_job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Print run_id
        run: |
           echo ${{ github.run_id  }}

      - name: print job name
        run: |
           echo ${{ github.job }}

      - name: Exit
        run: exit 1

      - name: Cancel all other jobs on failure
        if: failure()
        run: |
           echo "cancel all other jobs"
           gh run cancel ${{ github.run_id  }}
        env:
           GH_TOKEN: ${{ github.token }}

  checklist_job2:
    runs-on: ubuntu-latest
    name: checklist_job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print run_id
        run: |
           echo ${{ github.run_id  }}

      - name: sleep 180
        run: sleep 180

      - name: Deploy
        if: cancelled()
        run: |
           echo "this was cancelled"
