name: QA 
on: pull_request

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: Checklist
    steps:
      - name: Checkout ifixit
        uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: ./.github/actions/setup-ci-env-vars
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print url
        run: |
          echo "${{ steps.get_action_job_url.outputs.job-url }}"
  testing_job1:
    runs-on: ubuntu-latest
    name: Checklist1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Get Action Run Info
        uses: octokit/request-action@v2.x
        id: get_action_run
        with:
          route: GET /repos/{owner}/{repo}/actions/runs/${{github.run_id}}/jobs
          owner: batbattur
          repo: All
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get job url
        run: |
          echo "WORKFLOW_JOB_URL=$(echo $json_var | jq '.jobs | .[] | .html_url' | sed 's/?check_suite_focus=true//')" >> $GITHUB_ENV
        env:
          json_var: ${{ steps.get_action_run.outputs.data }}
      - name: Print url
        run: |
          echo $WORKFLOW_JOB_URL
