name: QA 
on: pull_request

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: Checklist
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checklist  
        uses: batbattur/contextual-qa-checklist-action@69aa588807d6b71c7e4224c12461a4e0070af2e6
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          input-file: '.github/QAchecklist.yml'
          comment-header: "Hey, by the way, we noticed the following changes:"
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Get Action Run Info
        uses: octokit/request-action@v2.x
        id: get_action_run
        with:
          route: GET /repos/{owner}/{repo}/actions/runs/${{github.run_id}}/jobs
          owner: batbattur
          repo: All
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get job url
        run: |
          echo $json_var | jq '.jobs | .[] | .html_url' | sed 's/?check_suite_focus=true//')
        env:
          json_var: ${{ steps.get_action_run.outputs.data }}
      - name: Print url
        run: |
          echo $WORKFLOW_JOB_URL
