name: Datadog

on:
   workflow_run:
      workflows:
         - '**'
      types:
         - completed

jobs:
   send:
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:
        - name: Event
          id: set-result
          uses: actions/github-script@v6
          with:
            script: |
              core.info(`${JSON.stringify(context.payload, undefined, 2)}`)
              
        - name: Get result
          run: echo "${{steps.set-result.outputs.result}}"

        - name: Get context using console
          id: set-result-console
          uses: actions/github-script@v6
          with:
            script: console.log(context)

        - name: Get result with console
          run: echo "${{steps.set-result-console.outputs.result}}"

        - name: Get result
          run: echo "${{steps.set-result.outputs.result}}"

        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
          run: echo "$GITHUB_CONTEXT"

        - name: TESTING
          run: echo "testing"
