name: Datadog

on:
   workflow_run:
      workflows:
         - '**'
      types:
         - completed

jobs:
   send:
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:
        - name: Event
          id: set-result
          uses: actions/github-script@v6
          with:
            script: |
              core.info(`${JSON.stringify(context.payload, undefined, 2)}`)
              
        - name: Get result
          run: echo "${{steps.set-result.outputs.result}}"

        - name: Get context using console
          id: set-result-console
          uses: actions/github-script@v6
          with:
            script: console.log(context)

        - name: Get result with console
          run: echo "${{steps.set-result-console.outputs.result}}"

        - name: Get result
          run: echo "${{steps.set-result.outputs.result}}"

        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
          run: echo "$GITHUB_CONTEXT"

        - name: TESTING
          run: echo "testing"

        - name: TESTING event
          run: echo "${{github.event.workflow_run.event}}"


        - name: TESTING event
          run: echo "${{github.event.workflow_run.event}}"

        - name: TESTING event
          if: github.event.workflow_run.event == 'pull_request'
          id: pull-number
          run: |
            echo "${{github.event.workflow_run.pull_requests}}"
            echo "${{github.event.workflow_run.pull_requests[0].number}}"
            echo "${{github.event.workflow_run.pull.requests[0].url}}"
            echo "pull-number=$(echo ${{github.event.workflow_run.pull_requests[0].number}})" >> $GITHUB_OUTPUT


        - name: Get Pull Info
          uses: octokit/request-action@v2.x
          if: github.event.workflow_run.event == 'pull_request'
          id: get_action_job_data
          with:
            route: GET /repos/${{ github.repository }}/pulls/${{ steps.pull-number.outputs.pull-number }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Get pull label and draft status
          if: github.event.workflow_run.event == 'pull_request'
          run: |
            JOB_DATA_JSON=$(echo $job_data_json | jq '.jobs | .[]? | select(.name == "${{ env.GITHUB_JOB_NAME }}")')
            echo "job-url=$(echo $JOB_DATA_JSON | jq '.html_url')" >> $GITHUB_OUTPUT
            echo "job-start-time=$(echo $JOB_DATA_JSON | jq '.started_at')" >> $GITHUB_OUTPUT
          env:
            job_data_json: ${{ steps.get_action_job_data.outputs.data }}

        - name: Get pull label and draft status
          if: github.event.workflow_run.event == 'pull_request'
          run: |
            LABELS=$(echo $job_data_json | jq '.labels | .[]? | .labels')
            TESTING_LABEL=$(echo $job_data_json | jq '.labels | .[]? | select(.labels == "testing")')
            DRAFT_STATUS=$(echo $job_data_json | jq '.draft')
          env:
            job_data_json: ${{ steps.get_action_job_data.outputs.data }}

        - name: Should be skipped
          run: echo "testing"

