name: Datadog

on:
   workflow_run:
      workflows:
         - '**'
      types:
         - completed

jobs:
   send:
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
          run: echo "$GITHUB_CONTEXT"

        - name: Testing pull_requests == '[]'
          if: github.event.workflow_run.pull_requests == '[]'
          run: echo "testing"

        - name: Testing pull_requests == ''
          if: github.event.workflow_run.pull_requests == ''
          run: echo "testing"
          

        - name: Get Pull Info
          uses: octokit/request-action@v2.x
          if: github.event.workflow_run.event == 'pull_request'
          id: get_action_job_data
          with:
            route: GET /repos/${{ github.repository }}/pulls/${{github.event.workflow_run.pull_requests[0].number}}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Skip sending metrics on draft pulls or the testing label 
          id: skip-check
          if: github.event.workflow_run.event == 'pull_request'
          run: |
            TESTING_LABEL=$(echo $job_data_json | jq '.labels | .[]? | select(.name == "${{ env.skip-label }}")')
            DRAFT_STATUS=$(echo $job_data_json | jq '.draft')
            if [ -n "$TESTING_LABEL" ] || [ "$DRAFT_STATUS" == "true" ]
            then
              echo "Skipping to send the workflow metrics data to Datadog."
              echo "skip=true" >> $GITHUB_OUTPUT
            fi
          env:
            job_data_json: ${{ steps.get_action_job_data.outputs.data }}
            skip-label: bug

        - name: Should be skipped
          if: "! (github.event.workflow_run.event == 'pull_request' && steps.skip-check.outputs.skip == 'true')"
          run: echo "testing"

