name: FAST DEPLOY
on: workflow_dispatch
  #  pull_request: 
  #  push:
  #     branches:
  #        - master
   

env:
  COMMIT: ${{ github.sha }}

jobs:
  fast-deploy:
    runs-on: ubuntu-latest
    name: fast-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: fast-deploy
        uses: ./.github/actions/validate
        with:
          validate: 'false'
