name: Renovate

on:
   workflow_dispatch:
   schedule:
      - cron: '0/30 * * * *'

jobs:
   renovate:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v3

      - name: Self-hosted Renovate
           uses: renovatebot/github-action@v36.0.0
           with:
              configurationFile: renovate.json
              token: ${{ secrets.RENOVATE_TOKEN }}
           env:
              LOG_LEVEL: 'debug'
