name: Renovate

on:
   workflow_dispatch:
   schedule:
      - cron: '0/30 * * * *'

jobs:
   renovate:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v3
           with:
              submodules: recursive

        #  - name: Run
        #    run: |
        #       git submodule sync
        #       git submodule update --init --recursive

         - name: Self-hosted Renovate
           uses: renovatebot/github-action@v36.0.3
           with:
              configurationFile: renovateConfig.js
              token: ${{ secrets.RENOVATE_TOKEN }}
           env:
              LOG_LEVEL: 'debug'
              token: ${{ secrets.FONT_AWESOME_TOKEN }}
