name: TEST
on:
   pull_request: 
   push:
      branches:
         - master
env:
  COMMIT: ${{ github.sha }}

jobs:
  test1:
    runs-on: ubuntu-latest
    name: checklist_job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: echo COMMIT
        run: echo "$COMMIT"
        
      - name: echo GITHUB_SHA
        run: echo "$GITHUB_SHA"

  test2:
    runs-on: ubuntu-latest
    name: checklist_job2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: echo COMMIT
        run: echo "$COMMIT"
        
      - name: echo GITHUB_SHA
        run: echo "$GITHUB_SHA"
        
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJSON(github) }}
#         run: echo "$GITHUB_CONTEXT"

#       - name: Print TESTING
#         run: |
#            echo ${{ github.workflow  }}
#            echo ${{ github.ref }}
#            echo ${{ github.run_number }}
#         shell: bash
        
#       - name: Print github.sha 
#         run: echo ${{ github.sha }}

#       - name: Print github.event.pull_request.head.sha
#         run: echo ${{ github.event.pull_request.head.sha }}        
        
        
#       - name: Get head commit sha from the push event and set it to push_head_commit env
#         run: echo "push_head_commit=$(echo $COMMITS_JSON | jq ".[length - 2].id")" >> $GITHUB_ENV
#         shell: bash
#         env:
#             COMMITS_JSON: ${{ toJSON(github.event.commits) }}

#       - name: Print sha of the head commit
#         run: echo "$push_head_commit"
#         shell: bash
