name: Set CI Environment Variables
description: Set CI Environment Variables
runs:
   using: 'composite'
   steps:
      - name: Get Action Job Info
        uses: octokit/request-action@v2.x
        id: get_action_job_data
        with:
           route: GET /repos/{owner}/{repo}/actions/runs/${{github.run_id}}/jobs
           owner: batbattur
           repo: All

      - name: Get job url
        id: get_action_job_url
        run:
           | 
           TESTING=$(echo $job_data_json | jq '.jobs | .[]? | select(.name == "${{ env.GITHUB_JOB_NAME }}")
           echo "::set-output name=job-url::$(echo $TESTING | jq '.html_url')"
           echo "::set-output name=job-start-time::$(echo $TESTING | jq '.started_at')"

        env:
           job_data_json: ${{ steps.get_action_job_data.outputs.data }}
        shell: bash
        
      - name: Print url
        run: 
            |
            echo $url
            echo "$url"
            echo "${{ env.GITHUB_JOB_NAME }}"
            echo  ${{ steps.get_action_job_url.outputs.job-url }}
            echo "${{ steps.get_action_job_url.outputs.job-url }}"
            echo  ${{ steps.get_action_job_url.outputs.job-start-time }}
            echo "testing"
        
        env:
           url: ${{ steps.get_action_job_url.outputs.job-url }}
        shell: bash
