name: Set CI Environment Variables
description: Set CI Environment Variables
runs:
   using: 'composite'
   steps:        
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJSON(github) }}
      #   run: echo "$GITHUB_CONTEXT"
      #   shell: bash

      # - name: echo COMMIT
      #   run: echo "$COMMIT"
      #   shell: bash
        
      # - name: RUN ATTEMPT AND NUMBER
      #   shell: bash
      #   run: |
      #      echo "RUN ATTEMPT: ${{ github.run_attempt }}"
      #      echo "RUN NUMBER: ${{ github.run_number }}"

      # - name: check-attempt
      #   shell: bash
      #   id: check-attempt
      #   run: |
      #      echo "INSIDE CHECK ATTEMPT"
      #      echo "RUN ATTEMPT: ${{ github.run_attempt }}"
      #      echo "first_attempt=$(echo ${{ github.run_attempt }} == 1 | bc)" >> $GITHUB_OUTPUT

      # - name: Exit if not the first attempt
      #   if:  steps.check-attempt.outputs.first_attempt == 0
      #   shell: bash
      #   run: |
      #      echo "INSIDE Exit if not the first attempt"
      #      echo "EXITING"
      #      exit 1


      # - name: check-attempt output
      #   shell: bash
      #   run: |
      #      echo "CHECKING check-attempt output:" ${{ steps.check-attempt.outputs.first_attempt }}
      #      echo ${{ steps.check-attempt.outputs.first_attempt }}
      #      exit 1

      - name: TEST 3
        shell: bash
        if:  github.run_attempt > 1
        run: |
           echo "RUN ATTEMPT: ${{ github.run_attempt }}"
           echo "is_rerun='true'" >> $GITHUB_OUTPUT
           exit 1

      # - name: failure
      #   shell: bash
      #   if: failure()
      #   run: |
      #      echo "RUNNING THE FAILURE CASE"

      # - name: alwaysaaa
      #   shell: bash
      #   if:  always()
      #   run: |
      #      echo "RUNNING THE ALWAYS CASE"
           
