name: Set CI Environment Variables
description: Set CI Environment Variables
runs:
   using: 'composite'
   steps:
      - name: Get Action Job Info
        uses: octokit/request-action@v2.x
        id: get_action_job_data
        with:
           route: GET /repos/{owner}/{repo}/actions/runs/${{github.run_id}}/jobs
           owner: batbattur
           repo: All

      - name: Get job url
        id: get_action_job_url
        run:
           | 
           echo "::set-output name=job-url::$(echo $job_data_json | jq '.jobs | .[]? | select(.html_url == "${{ env.GITHUB_JOB_NAME }}") | .html_url' | sed 's/?check_suite_focus=true//g')"
        env:
           job_data_json: ${{ steps.get_action_job_data.outputs.data }}
        shell: bash
        
      - name: Test
        run:
           | 
           echo ${{ steps.get_action_job_url.outputs.job-url }}
        shell: bash
