name: Set CI Environment Variables
description: Set CI Environment Variables
runs:
   steps:        
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        shell: bash

      - name: echo COMMIT
        run: echo "$COMMIT"
        shell: bash
