name: Set CI Environment Variables
description: Set CI Environment Variables
runs:
   using: 'composite'
   steps:
        
      - name: Print url
        run: 
            |
            pwd
            echo ${{ github.workspace }}
            ls /var/www
            tree
        shell: bash
