name: Set CI Environment Variables
description: Set CI Environment Variables
runs:
   steps:
      - name: Set Coverage Environment Variables on master branch
        run: |
           echo "DEPLOY_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
           echo "TESTINGAAA"
        shell: bash
        if: github.event.pull_request.head.ref == 'master'

      - name: Set Coverage Environment Variables on non-master branc
        run: |
           echo "TESTING123"
           echo "CI_PULL_REQUEST=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
           echo "OVERRIDE_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
           echo "OVERRIDE_COMMIT=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
        shell: bash
       if: github.event.pull_request.head.ref != 'master'

