name: Set CI Environment Variables
description: Set CI Environment Variables
runs:
   steps:
      - name: Set Coverage Environment Variables on master branch
        if: github.event.pull_request.head.ref == 'master'
        run: |
           echo "DEPLOY_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
        shell: bash

      - name: Set Coverage Environment Variables on non-master branch
        if: github.event.pull_request.head.ref != 'master'
        run: |
           echo "CI_PULL_REQUEST=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
           echo "OVERRIDE_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
           echo "OVERRIDE_COMMIT=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
        shell: bash
        
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        shell: bash
