name: Set CI Environment Variables
description: Set CI Environment Variables
runs:
   using: 'composite'
   steps:        
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJSON(github) }}
      #   run: echo "$GITHUB_CONTEXT"
      #   shell: bash

      - name: echo COMMIT
        run: echo "$COMMIT"
        shell: bash
        
      - name: RUN ATTEMPT AND NUMBER
        shell: bash
        run: |
           echo "RUN ATTEMPT: ${{ github.run_attempt }}"
           echo "RUN NUMBER: ${{ github.run_number }}"

      - name: TEST 2
        shell: bash
        id: is-rerun
        if:  github.run_attempt > 1
        run: |
           echo "RUN ATTEMPT: ${{ github.run_attempt }}"
           echo "RUN NUMBER: ${{ github.run_number }}"
           echo "IS_RERUN='true'}" >> $GITHUB_OUTPUT
           exit 1
           
      - name: TEST 3
        shell: bash
        if:  github.run_attempt == 1
        run: |
           echo "RUN ATTEMPT: ${{ github.run_attempt }}"
           echo "RUN NUMBER: ${{ github.run_number }}"

      - name: failure
        shell: bash
        if:  failure() && steps.is-rerun.outputs.IS_RERUN !== 'true'
        run: |
           echo "RUN ATTEMPT: ${{ github.run_attempt }}"
           echo "RUN NUMBER: ${{ github.run_number }}"

      - name: always
        shell: bash
        if:  always() && steps.is-rerun.outputs.IS_RERUN !== 'true'
        run: |
           echo "RUN ATTEMPT: ${{ github.run_attempt }}"
           echo "RUN NUMBER: ${{ github.run_number }}"
           
